### ISSUE TITLE
Autre Plateforme que Instagram

### ISSUE THREAD

**Issue by hollisticated-horse** [laviondebernard/instagram#2]
Bonjour, 

j’apprécie beaucoup votre travail, à la fois pour la sensibilisation au problématiques écologiques engendrées par les pratiques mises en évidence, et aussi pour le message politique. 

Cependant, je me dis que ce serait sympa de voir les données être présentées sur d'autres plateformes qu'Instagram, peut-être plus ouvertes et respectueuses de la vie privée, comme Mastodon et Pixelfeld, pour n'en cité que quelques-unes.

On peut fork le projet pour l'adapter ?

**Comment by ioqt-00** [comment]
Bonjour, 

Je ne fais pas partie du projet, mais il est sous license MIT, qui est une des plus permissives. Globalement, vous pouvez en faire ce que vous voulez, et trouver le détail de ce qu'il est possible de faire dans LICENSE.txt
